### ISSUE TITLE
App ID deprecated

### ISSUE THREAD

**Issue by abaphnasc** [DevCrew-io/camerakit-flutter#20]
There is no need to pass app-id to Camera Kit anymore. You can get rid of that from docs and code.

**Comment by arslandevcrew** [comment]
@abaphnasc Thank you for opening the issue, it is fixed in this commit [9d05ca](https://github.com/DevCrew-io/camerakit-flutter/pull/21/commits/9d05ca32f7e47153cae3084d2a6a8d431c60d36b).
