### ISSUE TITLE
App crash after I clicking on  initLensList or openCamera

### ISSUE THREAD

**Issue by dokind** [DevCrew-io/camerakit-flutter#24]
**Describe the bug**
Example app is crashing after initLensList or openCamera

**To Reproduce**
1. I setup 3 constant id 

  /// List of group IDs for Camera Kit (TODO: Fill group ID here).
  static const List<String> groupIdList = ['your-group-ids'];
  /// optional: if you want to get single lense you can set it otherwise set empty sting
  /// The lens ID for Camera Kit (TODO: Fill lens ID here).
  static const cameraKitLensId = 'camera-kit-lens-id';
  /// The API token for Camera Kit in the staging environment (TODO: Fill API token here).
  static const cameraKitApiToken = 'your-api-token'; //TODO fill api token staging & production here
}

**Expected behavior**
It suppose to work like a example

**Comment by dokind** [comment]
Do I need to add more configurations inside info.plist ?

**Comment by WaseemAbbas-DevCrew** [comment]
@dokind make sure you have set the correct `API token` and `Group IDs`. You can check the logs in the console for crash details.

**Comment by dokind** [comment]
Actually just crashed nothing logged, I set project id in info.plist and it's worked thanks
