### ISSUE TITLE
Camera not launching [Black screen]

### ISSUE THREAD

**Issue by dokind** [DevCrew-io/camerakit-flutter#29]
**Describe the bug**
When I open lenses with 0.0.6 package camere not showing completely black

**To Reproduce**

**Expected behavior**
Camera launches and use lenses

**Screenshots**
![IMG_0476](https://github.com/DevCrew-io/camerakit-flutter/assets/60846467/52f1589f-9c96-4bc4-9737-f2323c30d191)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15 Pro Max]
 - OS: [e.g. iOS17.2]

**Additional context**

**Comment by najamsaqib-devcreew** [comment]
@dokind if you're testing over a simulator, it will not display the camera view. Please try to test on a real device.

**Comment by dokind** [comment]
Yes mine was physical device sir

**Comment by najamsaqib-devcreew** [comment]
So could you please share more details about this issue.
Is you face issue on both staging or production environment api token?

Note: Some time it took some time to load all lenses,
