### ISSUE TITLE
Camera Remains Active and Causes Lag After Closing Camera Screen

### ISSUE THREAD

**Issue by dokind** [DevCrew-io/camerakit-flutter#30]
**Describe the bug**
I am experiencing a bug where the camera on my physical device remains active even after I close the camera screen. This causes the camera's green light to stay on, and my mobile device starts to lag.

To Reproduce:
Steps to reproduce the issue:
Open the application.
Navigate to the 'Launch camera' option.
Tap on 'Close camera.'
Notice that the camera's green light remains illuminated, and the mobile device begins to lag.
Expected Behavior:
The expected behavior is that the application should stop using the camera when the 'Close camera' option is selected, causing the camera's green light to turn off.

Screenshots:
**Screenshots**
![IMG_0520](https://github.com/DevCrew-io/camerakit-flutter/assets/60846467/312535b9-291e-4f20-a3ea-17dcefb9426b)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 15 Pro Max]
 - OS: [e.g. iOS17.2]

**Additional context**
Also There are no backbutton when I launch group lens with no lens Id, no way to go back to flutter app. (Only way is use camera)

**Comment by dokind** [comment]
This is kinda serious I think. It effects performance of application. Memory usage increasing consistently and phone started to lagging

**Comment by dokind** [comment]
Any update on this behaviour ?

**Comment by WaseemAbbas-DevCrew** [comment]
We're looking into it.

**Comment by WaseemAbbas-DevCrew** [comment]
@dokind I cannot see any `close camera` option in the example. Can you please share a screenshot showing the Close Camera option.

**Comment by dokind** [comment]
Do we have close camera method? 
After I received camera result I displaying video and I closed that screen
Hoe to close camera?

**Comment by dokind** [comment]
> @dokind I cannot see any `close camera` option in the example. Can you please share a screenshot showing the Close Camera option.

That's what I looking for sir. I need close camera method because it's still working after I took result video

**Comment by najamsaqib-devcreew** [comment]
Hi @dokind, I identify this bug in current version and fixed in [bug-fixes](https://github.com/DevCrew-io/camerakit-flutter/tree/bug-fixes) development branch.

Soon we will merge it and release the new **0.0.7** version for bug fixes and some improvements.

Thanks
