### ISSUE TITLE
How to display Powered By snapChat logo like a example video

### ISSUE THREAD

**Issue by dokind** [DevCrew-io/camerakit-flutter#31]
**Describe the bug**
Some text are overflowing on my screen and Snap chat team required to have a Powered by snapChat logo
![IMG_0630](https://github.com/DevCrew-io/camerakit-flutter/assets/60846467/168465c9-56a4-47fd-8610-9f68e861b6df)

**To Reproduce**
1. I just launch camera

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone15 Pro Max]
 - OS: [e.g. iOS17.2]

**Additional context**
i
Also I not seeing Snap chat agreement pop up things

**Comment by MuhammamdArslanKhan** [comment]
@dokind It will be visible exclusively in the staging environment on Android; you won't encounter it in the production environment.

**Comment by najamsaqib-devcreew** [comment]
@dokind I see there is some issue in camera kit reference ui pod, It’s not load the `Localizable.strings` resources in iOS application. 

![imgonline-com-ua-twotoone-sK9d2oZM2q](https://github.com/DevCrew-io/camerakit-flutter/assets/127479013/663ce8d5-4ff2-4ad9-9c64-9465191a902b)

If you want to load strings and display powered by snapchat logo please do the following steps.
- Open iOS application in Xcode
- Select `Pods` Project -> `Pods -> SCCameraKitReferenceUI -> Resources -> Localizable.strings`
- In `Target Membership` at right side checked `SCCameraKitReferenceUI` Target

![ScreenRecording2024-01-10at4 44 12PM-ezgif com-video-to-gif-converter](https://github.com/DevCrew-io/camerakit-flutter/assets/127479013/43b14ee8-a275-4a3d-a01c-4927786176c2)
