### ISSUE TITLE
bad photo quality after taking the pic

### ISSUE THREAD

**Issue by sana2024** [DevCrew-io/camerakit-flutter#32]
hey, everything works fine but when i take the picture and save it to file the quality of the photo is very blurry and bad, any work around for that ???

this is taken on iphone 11
![IMG_8107 2](https://github.com/DevCrew-io/camerakit-flutter/assets/53705282/fba71806-a6b7-4cc7-bebf-dec8a4730504)

**Comment by najamsaqib-devcreew** [comment]
Hi @sana2024, I identify this bug and fixed in [bug-fixes](https://github.com/DevCrew-io/camerakit-flutter/tree/bug-fixes) development branch.

Soon we will releasing the new **0.0.7** version for bug fixes and some improvements.

Thanks
