### ISSUE TITLE
CameraKit: Invalid Api Token

### ISSUE THREAD

**Issue by fahmad480** [DevCrew-io/camerakit-flutter#39]
it's work fine on android, run it on VSCode, but for iOS when open camera kit or lens list show "CameraKit: Invalid Api Token", are there any additional variables in info.plist?

**Comment by najamsaqib-devcreew** [comment]
Hi @fahmad480,

It looks like you didn't set the configuration before using it. You need to set the configuration before using the camera kit as we did in the example project.

`  @override
  void initState() {
    super.initState();
    _cameraKitFlutterImpl.setCredentials(apiToken: Constants.cameraKitApiToken);
  }`
  
  Or Follow the documentation [How to Set Configuration](https://github.com/DevCrew-io/camerakit-flutter?tab=readme-ov-file#set-configuration)

**Comment by fahmad480** [comment]
My bad, i use example too, but i forget to add that on my new scene. Thanks, ⭐️ for this repo
